site_name: GitHub Self-Hosted AWS Runners

repo_name: philips-labs/terraform-aws-github-runner
repo_url: https://github.com/philips-labs/terraform-aws-github-runner
edit_uri: edit/npalm/mkdocs/docs/
use_directory_urls: false

plugins:
  - blog:

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.action.edit
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
nav:
  - Introduciton: index.md
  - Configuration: configuration.md
  - Setup: setup.md
  - Security: security.md
  - Modules:
    - Runners (root): generated/modules/public/runners.md
    - Multi Runners: generated/modules/public/multi-runner.md
    - AMI Housekeeper: generated/modules/public/ami-housekeeper.md
    - Lambda Downloader: generated/modules/public/download-lambda.md
    - Internal:
      - Runner: generated/modules/internal/runners.md
      - Syncer: generated/modules/internal/runner-binaries-syncer.md
      - SSM: generated/modules/internal/ssm.md
      - Webhook: generated/modules/internal/webhook.md
      - Webhooik GitHub App:: generated/modules/internal/webhook-github-app.md
  - Examples:
    - Oeverview: examples.md
    - Default: generated/examples/default.md
    - Multiple: generated/examples/multi-runner.md
    - Ephemeral: generated/examples/ephemeral.md
    - Ubuntu: generated/examples/arm64.md
    - ARM64: generated/examples/ubuntu.md
    - Windows: generated/examples/windows.md
    - Custom AMI: generated/examples/prebuilt.md
    - Lambda download: generated/examples/lambdas-download.md
    - Permissions boundary: generated/examples/permissions-boundary.md
